import { Noto_Sans_KR, Poppins } from "next/font/google";
import "@/styles/tailwind.css";
import Footer from "@/components/footer/Footer";
import Header from "@/components/header/Header";
import { getAuthenticatedAppForUser } from "@/lib/firebase/firebaseServer";

const notoSansKR = Noto_Sans_KR({
  variable: "--font-noto-sans-kr",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const popins = Poppins({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const { currentUser } = await getAuthenticatedAppForUser();
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${notoSansKR.variable} ${popins.variable} antialiased`}>
        <Header initialUser={currentUser ? currentUser.toJSON() : null} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
